### ISSUE TITLE
建议增加段落间的回车或缩进

### ISSUE THREAD

**Issue by jiexuecao** [ravenxrz/RubberTranslator#1]
建议翻译结果的每段段前增加回车再缩进两个字符或者增大段间距，现在**翻译多段内容却都排在一段**看起来密密麻麻的，不容易区分段落。

同时建议输入窗口允许输入回车，像这样的内容点击翻译后回车就消失了
![image](https://user-images.githubusercontent.com/36891161/82341178-a8d02400-9a22-11ea-8915-b395d7192dd6.png)
但是像这样人为的回车可以区分段落，或者定位内容位置

**Comment by ravenxrz** [comment]
好的，感谢反馈。
第一个问题，明天会进行优化，加入到下一个版本中。
第二个问题，试试关闭"文本格式化"功能，再进行翻译，应该是会保留段落格式的。

---原始邮件---
发件人: "jiexuecao"<notifications@github.com&gt;
发送时间: 2020年5月19日(周二) 晚上10:55
收件人: "ravenxrz/RubberTranslator"<RubberTranslator@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [ravenxrz/RubberTranslator] 建议增加段落间的回车或缩进 (#1)




 
建议翻译结果的每段段前增加回车再缩进两个字符或者增大段间距，现在翻译多段内容却都排在一段看起来密密麻麻的，不容易区分段落。
 
同时建议输入窗口允许输入回车，像这样的内容点击翻译后回车就消失了
 
 但是像这样人为的回车可以区分段落，或者定位内容位置

**Comment by ravenxrz** [comment]
@jiexuecao 忘说了，谷歌翻译的翻译结果会统一去掉所有换行。百度和有道支持保留格式，但需要自行配置key&value.
