### ISSUE TITLE
建议功能：窗口大小调整后固定

### ISSUE THREAD

**Issue by TommyMerlin** [ravenxrz/RubberTranslator#2]
目前的窗口大小在调整好后如果来回切换模式后大小边又会变为调整以前的大小，
比较影响使用体验，
像 CopyTranslator 在调整完窗口大小之后不管是切换模式亦或是关掉重新打开都不会影响窗口大小，
希望可以添加一个保留窗口大小参数的 feature。

**Comment by ravenxrz** [comment]
已添加，下一个版本会支持。
