### ISSUE TITLE
更新完一直提示翻译失败

### ISSUE THREAD

**Issue by TommyMerlin** [ravenxrz/RubberTranslator#3]
版本：v3.3.3
![Snipaste_2021-02-01_15-15-40](https://user-images.githubusercontent.com/32566324/106426450-96a6f080-64a0-11eb-96ad-66bf5cc6002c.png)

**Comment by ravenxrz** [comment]
你的百度api配置了吗？



---原始邮件---
发件人: "HuYe"<notifications@github.com&gt;
发送时间: 2021年2月1日(周一) 下午3:18
收件人: "ravenxrz/RubberTranslator"<RubberTranslator@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [ravenxrz/RubberTranslator] 更新完一直提示翻译失败 (#3)




 
版本：v3.3.3

**Comment by TommyMerlin** [comment]
配置了，更新前使用是正常的。

**Comment by ravenxrz** [comment]
把log文件邮箱发我一下。zhang.xingrui@foxmail.com



---原始邮件---
发件人: "HuYe"<notifications@github.com&gt;
发送时间: 2021年2月2日(周二) 上午9:20
收件人: "ravenxrz/RubberTranslator"<RubberTranslator@noreply.github.com&gt;;
抄送: "Raven"<zhang.xingrui@foxmail.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题: Re: [ravenxrz/RubberTranslator] 更新完一直提示翻译失败 (#3)




 
配置了，更新前使用是正常的。

**Comment by ravenxrz** [comment]
> 配置了，更新前使用是正常的。

你之前的百度翻译应该是没有成功配置的，之所以旧版本可以翻译，是因为旧版本使用了【接力翻译】，也就是说当某个翻译器失败的时候，会自动选择另一个翻译器。默认的【谷歌翻译】是可以使用的。v3.3.3版本取消了【接力翻译】（是我不小心去掉了，又没测试完全），v3.3.4会再加上的。。

**Comment by TommyMerlin** [comment]
> 把log文件邮箱发我一下。zhang.xingrui@foxmail.com
> […](#)
> ---原始邮件--- 发件人: "HuYe"<notifications@github.com&gt; 发送时间: 2021年2月2日(周二) 上午9:20 收件人: "ravenxrz/RubberTranslator"<RubberTranslator@noreply.github.com&gt;; 抄送: "Raven"<zhang.xingrui@foxmail.com&gt;;"State change"<state_change@noreply.github.com&gt;; 主题: Re: [ravenxrz/RubberTranslator] 更新完一直提示翻译失败 (#3) 配置了，更新前使用是正常的。 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

已发

**Comment by ravenxrz** [comment]
> > 把log文件邮箱发我一下。[zhang.xingrui@foxmail.com](mailto:zhang.xingrui@foxmail.com)
> > […](#)
> > ---原始邮件--- 发件人: "HuYe"<[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2021年2月2日(周二) 上午9:20 收件人: "ravenxrz/RubberTranslator"<[RubberTranslator@noreply.github.com](mailto:RubberTranslator@noreply.github.com)>; 抄送: "Raven"<[zhang.xingrui@foxmail.com](mailto:zhang.xingrui@foxmail.com)>;"State change"<[state_change@noreply.github.com](mailto:state_change@noreply.github.com)>; 主题: Re: [ravenxrz/RubberTranslator] 更新完一直提示翻译失败 (#3) 配置了，更新前使用是正常的。 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 已发

你的百度翻译过于频繁， 百度API普通未认证用户 1s只能翻译一次。
